#!/usr/bin/env bash
# bootstrap-services.sh — Extract API keys from *arr containers and write .env.services
#
# LinuxServer *arr images auto-generate API keys in /config/config.xml on first boot.
# This script waits for each container to produce its config, extracts the <ApiKey>,
# then waits for arr-dashboard to become healthy before writing all connection details
# into .env.services for Playwright to consume.
#
# Usage: cd e2e/integration && bash bootstrap-services.sh
#
# Supports both docker-compose v1 and docker compose v2.

set -euo pipefail

SCRIPT_DIR="$(cd "$(dirname "${BASH_SOURCE[0]}")" && pwd)"
ENV_FILE="${SCRIPT_DIR}/.env.services"

# Timeout for waiting on config.xml (seconds)
CONFIG_TIMEOUT=120
# Timeout for dashboard health (seconds)
HEALTH_TIMEOUT=120
# Poll interval (seconds)
POLL_INTERVAL=3

# ── Helpers ────────────────────────────────────────────────────────────

log()  { echo "[bootstrap] $*"; }
fail() { echo "[bootstrap] ERROR: $*" >&2; exit 1; }

# Extract <ApiKey> from a container's /config/config.xml
# Args: $1 = container name, $2 = timeout
extract_api_key() {
  local container="$1"
  local timeout="$2"
  local elapsed=0
  local api_key=""

  # All log/progress output goes to stderr so stdout is clean for the return value
  echo "[bootstrap] Waiting for ${container} config.xml (timeout: ${timeout}s)..." >&2

  while [ "$elapsed" -lt "$timeout" ]; do
    # Try to read config.xml from the container
    local config_xml
    config_xml=$(docker exec "$container" cat /config/config.xml 2>/dev/null || echo "")

    if [ -n "$config_xml" ]; then
      # Extract ApiKey using grep + sed (portable, no xmllint dependency)
      api_key=$(echo "$config_xml" | grep -oP '<ApiKey>\K[^<]+' 2>/dev/null || echo "")

      if [ -n "$api_key" ]; then
        echo "[bootstrap]   ${container}: API key extracted (${#api_key} chars)" >&2
        echo "$api_key"
        return 0
      fi
    fi

    sleep "$POLL_INTERVAL"
    elapsed=$((elapsed + POLL_INTERVAL))
    echo -n "." >&2
  done

  echo "" >&2
  fail "${container}: config.xml not found or missing <ApiKey> after ${timeout}s"
}

# Wait for a health endpoint to return status="ok"
# Args: $1 = URL, $2 = label, $3 = timeout
wait_for_health() {
  local url="$1"
  local label="$2"
  local timeout="$3"
  local elapsed=0

  log "Waiting for ${label} health at ${url} (timeout: ${timeout}s)..."

  while [ "$elapsed" -lt "$timeout" ]; do
    local response
    response=$(curl -sf "$url" 2>/dev/null || echo "")

    if [ -n "$response" ]; then
      local status
      status=$(echo "$response" | grep -oP '"status"\s*:\s*"\K[^"]+' 2>/dev/null || echo "")

      if [ "$status" = "ok" ]; then
        log "  ${label}: healthy!"
        return 0
      fi
    fi

    sleep "$POLL_INTERVAL"
    elapsed=$((elapsed + POLL_INTERVAL))
    echo -n "."
  done

  echo ""
  fail "${label}: not healthy after ${timeout}s"
}

# ── Main ───────────────────────────────────────────────────────────────

log "=== Bootstrap Integration Services ==="
log ""

# 1. Extract API keys from each *arr container
SONARR_API_KEY=$(extract_api_key "e2e-sonarr" "$CONFIG_TIMEOUT")
RADARR_API_KEY=$(extract_api_key "e2e-radarr" "$CONFIG_TIMEOUT")
PROWLARR_API_KEY=$(extract_api_key "e2e-prowlarr" "$CONFIG_TIMEOUT")

log ""

# 2. Create media directories inside *arr containers (required for root folder API)
log "Creating media directories in containers..."
docker exec e2e-sonarr mkdir -p /config/media/tv
docker exec e2e-sonarr chown -R abc:abc /config/media
docker exec e2e-radarr mkdir -p /config/media/movies
docker exec e2e-radarr chown -R abc:abc /config/media
log "  Media directories created"

log ""

# 3. Wait for arr-dashboard to be healthy
wait_for_health "http://localhost:3000/health" "arr-dashboard (web)" "$HEALTH_TIMEOUT"
wait_for_health "http://localhost:3001/health" "arr-dashboard (api)" "$HEALTH_TIMEOUT"

log ""

# 4. Write .env.services
cat > "$ENV_FILE" << EOF
# Generated by bootstrap-services.sh — do not edit manually
# Internal URLs are used by arr-dashboard (inside Docker network)
# External URLs are used by Playwright/seed scripts (on the host)

# Sonarr
SONARR_API_KEY=${SONARR_API_KEY}
SONARR_URL=http://sonarr:8989
SONARR_EXTERNAL_URL=http://localhost:8989

# Radarr
RADARR_API_KEY=${RADARR_API_KEY}
RADARR_URL=http://radarr:7878
RADARR_EXTERNAL_URL=http://localhost:7878

# Prowlarr
PROWLARR_API_KEY=${PROWLARR_API_KEY}
PROWLARR_URL=http://prowlarr:9696
PROWLARR_EXTERNAL_URL=http://localhost:9696

# Dashboard
DASHBOARD_URL=http://localhost:3000
DASHBOARD_API_URL=http://localhost:3001
EOF

log "Wrote ${ENV_FILE}"
log ""
log "=== Bootstrap Complete ==="
log ""
log "Next: pnpm e2e:integration"
