import { defineConfig, devices } from "@playwright/test";
import path from "node:path";
import { config } from "dotenv";

// Load service connection details generated by bootstrap-services.sh
config({ path: path.join(__dirname, ".env.services") });

const authFile = path.join(__dirname, ".playwright-auth/integration-user.json");

export default defineConfig({
	testDir: ".",

	// Sequential — tests build on each other (setup → specs in order)
	fullyParallel: false,
	workers: 1,

	// Container responses are slower than local dev
	timeout: 60_000,

	forbidOnly: !!process.env.CI,
	retries: process.env.CI ? 2 : 1,

	reporter: process.env.CI
		? [["list"], ["html", { open: "never", outputFolder: "../../playwright-report-integration" }]]
		: [["html", { outputFolder: "../../playwright-report-integration" }], ["list"]],

	use: {
		baseURL: process.env.DASHBOARD_URL || "http://localhost:3000",
		trace: "on-first-retry",
		screenshot: "only-on-failure",
		video: "retain-on-failure",
	},

	expect: {
		timeout: 15_000,
	},

	projects: [
		// Setup: register user + add service instances
		{
			name: "setup",
			testMatch: /fixtures\/.*\.setup\.ts/,
		},

		// Integration specs: run after setup, use saved auth state
		{
			name: "integration",
			testDir: "./specs",
			testMatch: /.*\.spec\.ts/,
			use: {
				...devices["Desktop Chrome"],
				storageState: authFile,
			},
			dependencies: ["setup"],
		},
	],
});
